version: 2

jobs:
  build:
    docker:
      - image: circleci/ruby:2.5.1-node

    steps:
      - checkout

      - restore_cache:
          key: apprenticeio-{{ arch }}-{{ checksum "Gemfile.lock" }}

      - run:
          name: Install Ruby dependencies
          command: bundle install --path vendor/bundle

      - save_cache:
          key: apprenticeio-{{ arch }}-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

      - run:
          name: Build Middleman site
          command: bin/build

      - run:
          name: Run HTMLProofer
          command: bin/test
